### ISSUE TITLE
Implement Indodax.com

### ISSUE THREAD

**Issue by Rezaxtama** [emmtte/Cryptocurrency-Portfolio#31]
Dear Mr. Emmanuel 
Please help me for indodax.com

Thanks

Best Regards
Reza

**Comment by ManuCart** [comment]
Hi and Welcome
Have you got the link for the API?

**Comment by Rezaxtama** [comment]
Thanks for response

this is link for API

https://indodax.com/downloads/BITCOINCOID-API-DOCUMENTATION.pdf

**Comment by ManuCart** [comment]
Should be about the same as :
https://github.com/ManuCart/Cryptocurrency-Portfolio/blob/master/API_Poloniex.js
Need time to do it or you can try by yourself and make a request

**Comment by Rezaxtama** [comment]
he he he i try by my self 3 hours ago, but stack..nothing happen on sheet market..sorry for my english language, but thanks for your help & response

**Comment by emmtte** [comment]
No plan to add
