### ISSUE TITLE
Kucoin API update

### ISSUE THREAD

**Issue by Popcorn2018** [emmtte/Cryptocurrency-Portfolio#41]
Hi,

Not sure if you're updating this but Kucoin has upgraded their API and the old code doesn't work.

Seems to want a 44 character signature, not 64.

**Comment by lukeon2** [comment]
Fix for kucoin v2:

var nowDate = new Date().getTime();
 
 var nowStr = '' + nowDate;
 var strForSign = nowStr + 'GET' + '/api/v1/accounts'+''
 var signature = Utilities.computeHmacSignature(Utilities.MacAlgorithm.HMAC_SHA_256, strForSign, secret);
 
 var url = 'https://api.kucoin.com/api/v1/accounts';
 var options = {
   'headers' : {
     'KC-API-KEY': key,
     'KC-API-TIMESTAMP': nowStr,
     'KC-API-SIGN': Utilities.base64Encode(signature),
     'KC-API-PASSPHRASE': 'pass-from-'
    }
 }
 
var jsondata = UrlFetchApp.fetch(url, options);

**Comment by markclift** [comment]
Hi guys, I keep getting "Invalid KC-API-PASSPHRASE". Any ideas?

**Comment by markclift** [comment]
> Hi guys, I keep getting "Invalid KC-API-PASSPHRASE". Any ideas?

Fixed it - if the API key is V2 then the passphrase needs to be sent encrypted in the same way that the signature is

**Comment by emmtte** [comment]
Pull request accepted
