### ISSUE TITLE
Missing File | Page 404

### ISSUE THREAD

**Issue by UlyssesL** [emmtte/Cryptocurrency-Portfolio#44]
I want to create the jsSHA.js file but the content from https://github.com/Caligatio/jsSHA/blob/master/src/sha.js brings me to a 404 page.

Thank you

**Comment by 0xbea** [comment]
Try https://github.com/Caligatio/jsSHA/blob/master/dist/sha.js

**Comment by emmtte** [comment]
Corrected in README.md
