### ISSUE TITLE
Request: Telegram

### ISSUE THREAD

**Issue by elRadix** [emmtte/Cryptocurrency-Portfolio#7]
This is a feature request to add Telegram functionality to send a update of your portfolio to your own Telegram bot or channel.

Like a list of coins that you want to be reminded on a regular basis.

**Comment by ManuCart** [comment]
Good Idea, but personnaly I use Google Inbox to receive a pdf market sheet
see in README section optional how to use this

**Comment by ManuCart** [comment]
For telegram try with this
https://github.com/ocordova/gas-telegram-bot/blob/master/code.gs
or this
````
function sendTelegramNotification(botSecret, chatId, body) {
var response = UrlFetchApp.fetch("https://api.telegram.org/bot" + botSecret + "/sendMessage?text=" + encodeURIComponent(body) + "&chat_id=" + chatId + "&parse_mode=HTML");
}
````

**Comment by emmtte** [comment]
No plan to add
